---
- name: "Ensure configured Homebrew taps are tapped"
  community.general.homebrew_tap:
    name: "{{ item.name | default(item) }}"
    url: "{{ item.url | default(omit) }}"
    state: "present"
  loop: "{{ homebrew_taps }}"

- name: "Ensure configured Homebrew packages are installed"
  community.general.homebrew:
    name: "{{ item.name | default(item) }}"
    install_options: "{{ item.install_options | default(omit) }}"
    state: "present"
  loop: "{{ homebrew_installed_packages }}"

- name: "Ensure configured Homebrew Cask apps are installed"
  community.general.homebrew_cask:
    name: "{{ item.name | default(item) }}"
    install_options: "{{ item.install_options | default(omit) }}"
    accept_external_apps: "{{ homebrew_cask_accept_external_apps }}"
    state: "present"
  loop: "{{ homebrew_cask_installed_apps }}"

- name: "Upgrade all Homebrew packages (if configured)"
  community.general.homebrew:
    update_homebrew: true
    upgrade_all: true
  when: "homebrew_upgrade_all_packages | bool"
