---
- name: "Increase keyboard repeat rate"
  community.general.osx_defaults:
    domain: "NSGlobalDomain"
    key: "{{ item.key }}"
    value: "{{ item.value }}"
    type: "{{ item.type }}"
    state: "present"
  loop:
    - { key: "InitialKeyRepeat", value: "10", type: "int" }
    - { key: "KeyRepeat", value: "2", type: "int" }
    - { key: "ApplePressAndHoldEnabled", value: "false", type: "boolean" }
