---
homebrew_upgrade_all_packages: false

homebrew_taps:
  - "localsend/localsend"

homebrew_installed_packages:
  - "awscli"
  - "azure-cli"
  - "bash"
  - "coreutils"
  - "curl"
  - "findutils"
  - "fzf"
  - "gawk"
  - "gh"
  - "git"
  - "git-absorb"
  - "git-extras"
  - "gnu-sed"
  - "gnu-tar"
  - "gnupg"
  - "go"
  - "gron"
  - "imagemagick"
  - "jenv"
  - "jq"
  - "mas"
  - "massren"
  - "maven"
  - "moreutils"
  - "mpv"
  - "mvndaemon/mvnd/mvnd@1"
  - "ncdu"
  - "neovim"
  - "node"
  - "pyenv"
  - "python"
  - "ripgrep"
  - "rsync"
  - "shellcheck"
  - "shfmt"
  - "sops"
  - "sshuttle"
  - "stow"
  - "tmux"
  - "tree"
  - "vim"
  - "watch"
  - "wget"
  - "xmlstarlet"
  - "zsh"

homebrew_cask_accept_external_apps: false
homebrew_cask_installed_apps:
  - "adobe-acrobat-reader"
  - "android-file-transfer"
  - "backuploupe"
  - "betterdisplay"
  - "dbeaver-community"
  - "firefox"
  - "firefox@nightly"
  - "font-fira-code"
  - "font-fira-mono"
  - "gimp"
  - "google-chrome"
  - "google-cloud-sdk"
  - "iterm2"
  - "jdk-mission-control"
  - "jetbrains-toolbox"
  - "joplin"
  - "jordanbaird-ice"
  - "keeper-password-manager"
  - "localsend"
  - "logi-options-plus"
  - "meetingbar"
  - "orbstack"
  - "protonvpn"
  - "rectangle"
  - "slack"
  - "spotify"
  - "stats"
  - "tailscale"
  - "temurin"
  - "utm"
  - "visual-studio-code"
  - "visualvm"
  - "zoom"

mh_hostname: "argon"
mh_localhostname: "argon"
mh_computername: "argon"
mh_netbiosname: "argon"
