---
homebrew_upgrade_all_packages: false

homebrew_taps:
  - "localsend/localsend"
  - "mvndaemon/homebrew-mvnd"

homebrew_installed_packages:
  - "bash"
  - "coreutils"
  - "curl"
  - "fzf"
  - "gawk"
  - "gh"
  - "git"
  - "git-absorb"
  # - "git-extras"
  - "gnu-sed"
  - "gnu-tar"
  - "go"
  # - "gpg2"
  - "jenv"
  - "jq"
  # - "mas"
  - "maven"
  # - "mpv"
  # - "ncdu"
  - "neovim"
  - "python"
  - "shellcheck"
  - "shfmt"
  - "sops"
  # - "stow"
  # - "tmux"
  # - "tree"
  # - "vim"
  # - "watch"
  - "xmlstarlet"
  - "awscli"
  - "azure-cli"
  - "zsh"

# homebrew_cask_appdir: "/Applications"
homebrew_cask_accept_external_apps: false
homebrew_cask_installed_apps:
  - "dbeaver-community"
  - "docker"
  - "firefox"
  - "firefox@nightly"
  - "font-fira-code"
  - "font-fira-mono"
  - "gimp"
  - "google-chrome"
  - "google-cloud-sdk"
  - "iterm2"
  - "jetbrains-toolbox"
  - "joplin"
  - "logi-options-plus"
  - "meetingbar"
  - "mvnd@1"
  - "slack"
  - "spotify"
  - "visual-studio-code"
  - "visualvm"
  - "zoom"

pip_installed_packages:
  - "ansible"
  - "paramiko"
  - "yamllint"
  - "ansible-lint"
