---
- hosts: "all"

  vars_files:
    - "default.config.yml"

  pre_tasks:
    - name: "Merge variables"
      include_vars: "{{ item }}"
      with_fileglob:
        - "{{ playbook_dir }}/config.yml"
      tags: ["always"]

  roles:
    - role: "homebrew"
      tags: ["homebrew"]
    # - role: "mas"
    #   tags: ["mas"]
    - role: "defaults"
      tags: ["defaults"]
