---
collections:
  # TODO: Add constraint of >=1.3.0 to avoid hitting https://github.com/ansible-collections/community.general/pull/1038
  # - name: "community.general"
  # TODO: Remove below once 1.3.0 is released
  - name: "https://github.com/ansible-collections/community.general"
    type: "git"
    version: "4c379bd3b2147710c3e7a1d900cddf47a6b7cd42"
